
CREATE DATABASE IF NOT EXISTS AfricaMusic;

-- CREATE USER 'boris'@'%' IDENTIFIED BY 'boris_1';
-- GRANT ALL ON AfricaMusic.* TO 'boris'@'%';
use AfricaMusic;

CREATE TABLE IF NOT EXISTS  COUNTRIES(
country INT PRIMARY KEY AUTO_INCREMENT,
Name_Country VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS  ARTISTS(
artist INT PRIMARY KEY AUTO_INCREMENT,
Name_Artist VARCHAR(30)  NOT NULL UNIQUE,
Image_Artist VARCHAR(20),
country INT,
FOREIGN KEY (country) REFERENCES COUNTRIES(country)
);


CREATE TABLE IF NOT EXISTS  ALBUMS(
album INT PRIMARY KEY AUTO_INCREMENT,
Title_Album VARCHAR(20)NOT NULL UNIQUE,
Release_date date,
Cover_Album VARCHAR(30),
CONSTRAINT ck_date CHECK (Release_date <> '00-00-00')
);

CREATE TABLE IF NOT EXISTS  GENRES(
genre INT PRIMARY KEY AUTO_INCREMENT,
Title_Genre VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS  SONGS(
song INT PRIMARY KEY AUTO_INCREMENT,
Name_Music VARCHAR(20) NOT NULL,
Source_Music VARCHAR(20) NOT NULL,
genre INT,
FOREIGN KEY (genre) REFERENCES GENRES(genre)

);

CREATE TABLE IF NOT EXISTS  ArtistAlbum(
artist INT, 
album INT, 
FOREIGN KEY (artist) REFERENCES ARTISTS(artist),
FOREIGN KEY (album) REFERENCES ALBUMS(album),
PRIMARY KEY(artist,album)
);

CREATE TABLE IF NOT EXISTS  AlbumMusic(
song INT,
album INT,
FOREIGN KEY (song) REFERENCES SONGS(song),
FOREIGN KEY (album) REFERENCES ALBUMS(album),
PRIMARY KEY(song,album),
INDEX `inx_AS` (song,album)

);

