CREATE DATABASE AfricaMusic;
use AfricaMusic;


CREATE TABLE COUNTRIES(
country INT PRIMARY KEY AUTO_INCREMENT,
Name_Country VARCHAR(30)
);

CREATE TABLE ARTISTS(
artist INT PRIMARY KEY AUTO_INCREMENT,
Name_Artist VARCHAR(30)  NOT NULL UNIQUE,
Image_Artist VARCHAR(20),
country INT,
FOREIGN KEY (country) REFERENCES COUNTRIES(country)
);


CREATE TABLE ALBUMS(
album INT PRIMARY KEY AUTO_INCREMENT,
Title_Album VARCHAR(20)NOT NULL UNIQUE,
Release_date date,
Cover_Album VARCHAR(30)
);

CREATE TABLE GENRES(
genre INT PRIMARY KEY AUTO_INCREMENT,
Title_Genre VARCHAR(20)
);

CREATE TABLE SONGS(
song INT PRIMARY KEY AUTO_INCREMENT,
Name_Music VARCHAR(20) NOT NULL,
Source_Music VARCHAR(20) NOT NULL,
genre INT,
FOREIGN KEY (genre) REFERENCES GENRES(genre)

);

CREATE TABLE ArtistAlbum(
artist INT, 
album INT, 
FOREIGN KEY (artist) REFERENCES ARTISTS(artist),
FOREIGN KEY (album) REFERENCES ALBUMS(album),
PRIMARY KEY(artist,album)
);

CREATE TABLE AlbumMusic(
song INT,
album INT,
FOREIGN KEY (song) REFERENCES SONGS(song),
FOREIGN KEY (album) REFERENCES ALBUMS(album),
PRIMARY KEY(song,album)

);
