CREATE TABLE `MEDICAMENTS` (
  `MEDICAMENT` INT NOT NULL AUTO_INCREMENT,
  `TYPE_MEDICAMENT` VARCHAR(50) NOT NULL,
  `QUANTITE_ADMINISTRE` INT NOT NULL,
  PRIMARY KEY (`MEDICAMENT`)
);

CREATE TABLE `NOURRITURE` (
  `NOURRITURE` INT NOT NULL AUTO_INCREMENT,
  `TYPE_NOURRITURE` VARCHAR(50) NOT NULL,
  `QUANTITE_NOURRITURE` INT NOT NULL,
  PRIMARY KEY (`NOURRITURE`)
);               
               
CREATE TABLE `POULAILLER` (
  `POULAILLER` INT NOT NULL AUTO_INCREMENT,
  `NBRE_MALES` INT NOT NULL,
  `NBRE_FEMELLES` INT NOT NULL,
  PRIMARY KEY (`POULAILLER`)
);
               
CREATE TABLE `RELEVE` (
  `RELEVE` INT NOT NULL AUTO_INCREMENT,
  `NBRE_PONTES` INT NOT NULL,
  `NBRE_DECES_MALES` INT NOT NULL,
  `NBRE_DECES_FEMELLES` INT NOT NULL,
  PRIMARY KEY (`RELEVE`)
);               
