CREATE TABLE IF NOT EXISTS `EMPIRE_POUSSINNY`.`MEDICAMENT` (
  `MEDICAMENT` INT NOT NULL AUTO_INCREMENT,
  `TYPE_MEDICAMENT` VARCHAR(50) NOT NULL,
  `QUANTITE_ADMINISTRE` INT NOT NULL,
  PRIMARY KEY (`MEDICAMENT`));

CREATE TABLE IF NOT EXISTS `EMPIRE_POUSSINNY`.`NOURRITURE` (
  `NOURRITURE` INT NOT NULL AUTO_INCREMENT,
  `TYPE_NOURRITURE` VARCHAR(50) NOT NULL,
  `QUANTITE_NOURRITURE` INT NOT NULL,
  PRIMARY KEY (`NOURRITURE`))'               
               
CREATE TABLE IF NOT EXISTS `EMPIRE_POUSSINNY`.`POULAILLER` (
  `POULAILLER` INT NOT NULL AUTO_INCREMENT,
  `NBRE_MALES` INT NOT NULL,
  `NBRE_FEMELLES` INT NOT NULL,
  PRIMARY KEY (`POULAILLER`));
               
CREATE TABLE IF NOT EXISTS `EMPIRE_POUSSINNY`.`RELEVE` (
  `RELEVE` INT NOT NULL AUTO_INCREMENT,
  `NBRE_PONTES` INT NOT NULL,
  `NBRE_DECES_MALES` INT NOT NULL,
  `NBRE_DECES_FEMELLES` INT NOT NULL,
  PRIMARY KEY (`RELEVE`));               
