-- CREER DATABASE
CREATE DATABASE EMPIRE_POUSSINNY;

-- CRÉER L'UTILISATEUR (LUXURY) ET MOT DE PASSE (password)
CREATE USER 'luxury'@'%' IDENTIFIED BY 'password';

-- DONNER TOUS LES PRIVILÈGES À L'UTILISATEUR (luxury) '%' = toutes les addresses
GRANT ALL ON EMPIRE_POUSSINNY.* TO 'luxury'@'%';

-- ACCÉDER À MON DATABASE 
USE EMPIRE_POUSSINNY;


CREATE TABLE `MEDICAMENTS` (
  `MEDICAMENT` INT NOT NULL AUTO_INCREMENT,
  `TYPE_MEDICAMENT` VARCHAR(50) NOT NULL,
  `QUANTITE_ADMINISTRE` INT NOT NULL,
  PRIMARY KEY (`MEDICAMENT`),
);

CREATE TABLE `NOURRITURES` (
  `NOURRITURE` INT NOT NULL AUTO_INCREMENT,
  `TYPE_NOURRITURE` VARCHAR(50) NOT NULL,
  `QUANTITE_NOURRITURE` INT NOT NULL,
  PRIMARY KEY (`NOURRITURE`)
);               
               
CREATE TABLE `POULAILLERS` (
  `POULAILLER` INT NOT NULL AUTO_INCREMENT,
  `NBRE_MALES` INT NOT NULL,
  `NBRE_FEMELLES` INT NOT NULL,
  PRIMARY KEY (`POULAILLER`)
);
               
CREATE TABLE `RELEVES` (
  `RELEVE` INT NOT NULL AUTO_INCREMENT,
  `NBRE_PONTES` INT NOT NULL,
  `NBRE_DECES_MALES` INT NOT NULL,
  `NBRE_DECES_FEMELLES` INT NOT NULL,
  PRIMARY KEY (`RELEVE`)
);               
