name: P.Projets

on: [push]

jobs:
  test-container:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      some-mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - name: Verify MySQL connection from container 
      run: |
        apt-get update
        apt-get install -y mysql-client
        mysql --host some-mysql --user root --password=password --execute "SHOW DATABASES;"
